/**
 * POST /api/voice/answer — RAG-grounded answer, server-side.
 * Body: { question: string }
 * 200:  { text: string, mode: "claude" | "template" }
 *
 * Works WITHOUT any API key (template synthesizer over the local corpus) —
 * the offline demo never loses the answer brain. With ANTHROPIC_API_KEY the
 * answer is generated by Claude (key stays on the server).
 */

import { collectAnswer, jsonError, serverAnswerFn } from "../_lib/server-voice";

export const dynamic = "force-dynamic";

const MAX_QUESTION_CHARS = 500;

export async function POST(req: Request): Promise<Response> {
  let body: { question?: unknown };
  try {
    body = (await req.json()) as { question?: unknown };
  } catch {
    return jsonError(400, "invalid_json");
  }
  const question = typeof body.question === "string" ? body.question.trim() : "";
  if (!question) return jsonError(400, "question_required");
  if (question.length > MAX_QUESTION_CHARS) return jsonError(400, "question_too_long");

  const { fn, mode } = serverAnswerFn();
  try {
    const text = await collectAnswer(fn, question);
    return Response.json({ text, mode });
  } catch (err) {
    return jsonError(502, `answer_failed: ${err instanceof Error ? err.message.slice(0, 200) : "unknown"}`);
  }
}
