/**
 * POST /api/voice/answer — RAG-grounded answer, server-side.
 * Body: { question: string }
 * 200:  { text: string, mode: "claude" | "template" }
 *
 * Works WITHOUT any API key (template synthesizer over the local corpus) —
 * the offline demo never loses the answer brain. With ANTHROPIC_API_KEY the
 * answer is generated by Claude (key stays on the server).
 */

import {
  collectAnswer,
  jsonError,
  rateLimited,
  serverAnswerFn,
} from "../_lib/server-voice";
import type { DialogTurn } from "../../../../lib/voice/gemini-answer";

export const dynamic = "force-dynamic";

const MAX_QUESTION_CHARS = 500;
const MAX_HISTORY_TURNS = 6;

function sanitizeHistory(raw: unknown): DialogTurn[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter(
      (t): t is { question: string; answer: string } =>
        !!t && typeof t.question === "string" && typeof t.answer === "string",
    )
    .slice(-MAX_HISTORY_TURNS)
    .map((t) => ({ question: t.question.slice(0, 500), answer: t.answer.slice(0, 1000) }));
}

export async function POST(req: Request): Promise<Response> {
  const limited = rateLimited(req);
  if (limited) return limited;

  let body: { question?: unknown; history?: unknown };
  try {
    body = (await req.json()) as { question?: unknown; history?: unknown };
  } catch {
    return jsonError(400, "invalid_json");
  }
  const question = typeof body.question === "string" ? body.question.trim() : "";
  if (!question) return jsonError(400, "question_required");
  if (question.length > MAX_QUESTION_CHARS) return jsonError(400, "question_too_long");

  const { fn, mode } = serverAnswerFn(sanitizeHistory(body.history));
  try {
    const text = await collectAnswer(fn, question);
    return Response.json({ text, mode });
  } catch (err) {
    console.error("[voice/answer] upstream error:", err);
    return jsonError(502, "answer_failed");
  }
}
